services: 
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=default'
    ports:
      - '5432:5432'